#!/bin/sh
cd $HOME/Pictures/Wallpapers

imgpath=$(zenity --width 1200 --height 600 --file-selection --filename=$HOME/Pictures/Wallpapers/ --title='Choose wallpaper')

swww img $imgpath --transition-step 100 --transition-fps 120 --transition-type grow --transition-duration 1
